name: xeus-kernel
channels:
  - https://prefix.dev/emscripten-forge-4x
  - https://prefix.dev/conda-forge
dependencies:
  # Kernels
  - xeus-python
  - xeus-sqlite
  - xeus-cpp
  - xeus-r
  - xeus-octave
  # Widgets
  - ipywidgets>=8.1.3,<9
  - ipyevents>=2.0.1
  - ipympl>=0.8.2
  - ipycanvas>=0.9.1
  - ipyleaflet
  # Python
  - numpy
  - matplotlib
  - pillow
  - plotly>=6,<7
  - bqplot
